project:
  type: website

website:
  google-analytics: "G-PKMQ2W4ZRC"
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Ex[1] DataVis with ggplot2
            href: handsOn_ex1.qmd
            
      - text: In-class Exercises
        menu: 
          - text: In-class Ex[1] S & P Summary with Tableau
            href: https://public.tableau.com/shared/5GXCKXPQD?:display_count=n&:origin=viz_share_link
            
      - text: Take-home Exercises
        menu: 
          - text: Take Home Exercise 1
            href: takeHome/th_ex1/th_ex1.qmd
     
      - text: Workshop & Notes
        menu:
          - text: BSWorkshop - Programming Statistical Graphics
            href: pnote/bsw_3.qmd
          - text: BSWorkshop - Build Statistical Model
            href: pnote/bsw_4.qmd
          - text: Shiny Workshop - Prof's Prototype
            href: https://tskam.shinyapps.io/prototype-ShinyIDEA/
          - text: Exploration 0 - Explore with Geospatial Data
            href: pnote/test0.qmd          
          - text: Exploration 1 - Pareto Chart
            href: pnote/test1.qmd
          - text: Exploration 2 - Pyramid & Other Charts
            href: pnote/test2.qmd
          - text: Exploration 3 - Interactive & Animated Pyramid Chart
            href: pnote/test3.qmd
          - text: Exploration 4 - Interactive Heatmap Chart
            href: pnote/test4.qmd
          - text: Exploration 5 - Time-Series Visualisation
            href: pnote/test5.qmd           
          - text: Personal Note
            href: pnote/note1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    

editor: visual

