project:
  type: website

website:
  google-analytics: "G-PKMQ2W4ZRC"
  cookie-consent: true
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Ex[1] DataVis with ggplot2
            href: handsOn_ex1.qmd
          - text: Ex[2] DataVis with Advanced ggplot2
            href: handsOn_ex2.qmd
          - text: Ex[3.1] Programming Interactive Visualisation
            href: handsOn_ex3.1.qmd
          - text: Ex[3.2] Programming Animation
            href: handsOn_ex3.2.qmd
          - text: Ex[3.3] Visualise Large Data Interactively
            href: handsOn_ex3.3.qmd          
          - text: Ex[4.1] Visual Statistical Analysis
            href: handsOn_ex4.1.qmd
          - text: Ex[4.2] Visualise Models
            href: handsOn_ex4.2.qmd
          - text: Ex[4.3] Visualising Uncertainty
            href: handsOn_ex4.3.qmd
          - text: Ex[4.4] Create Funnel Plot
            href: handsOn_ex4.4.qmd
          - text: Ex[5.1] Create Ternary Plot
            href: handsOn_ex5.1.qmd
          - text: Ex[5.2] Visualise Correlation Matrices
            href: handsOn_ex5.2.qmd
          - text: Ex[5.3] Create Heatmap
            href: handsOn_ex5.3.qmd
          - text: Ex[5.4] Create Parallel Coordinates Plot
            href: handsOn_ex5.4.qm
          - text: Ex[6.1] Create Calendar Heatmap
            href: handsOn_ex6.1.qmd
          - text: Ex[6.2] Create Cycle Plot
            href: handsOn_ex6.2.qmd
          - text: Ex[7.1] Choropleth Mapping
            href: handsOn_ex7.1.qmd
          - text: Ex[7.2] Visualise Geospatial Points
            href: handsOn_ex7.2.qmd 
          - text: Ex[7.3] Analytical Mapping
            href: handsOn_ex7.3.qmd 
            
            
      - text: In-class Exercises
        menu: 
          - text: Ex[1] S & P Summary with Tableau
            href: https://public.tableau.com/shared/5GXCKXPQD?:display_count=n&:origin=viz_share_link
          - text: Ex[3] Programming Interactive Data Visualisation
            href: inClass/inClass_ex03/inClass_ex3.qmd
          - text: Ex[4] Programming Interactive Data Visualisation 2
            href: inClass/inClass_ex04/inClass_ex4.qmd
          - text: Ex[5] Visualise Correlation Matrices
            href: inClass/inClass_ex05/inClass_ex5.qmd
          - text: Ex[6] Visualise Time-series Data
            href: inClass/inClass_ex06/inClass_ex6.qmd
          - text: Ex[7] Visualise Geospatial Analysis
            href: inClass/inClass_ex07/inClass_ex7.qmd
            
      - text: Take-home Exercises
        menu: 
          - text: Ex[1] Trellis Population Pyramids
            href: takeHome/th_ex1/th_ex1.qmd
          - text: Ex[2] DataViz Makeover for Trellis Population Pyramids
            href: takeHome/th_ex2/th_ex2.qmd
          - text: Ex[3] Resale Prices for Singapore Public Housing Property
            href: takeHome/th_ex3/th_ex3.qmd
          - text: Ex[4] Singapore Merchandise Trade from 2020 to 2022
            href: takeHome/th_ex4/th_ex4.qmd
     
      - text: Workshop & Notes
        menu:
          - text: BSWorkshop - Programming Statistical Graphics
            href: pnote/bsw_3.qmd
          - text: BSWorkshop - Build Statistical Model
            href: pnote/bsw_4.qmd
          - text: BSWorkshop - Build Predictive Model
            href: pnote/bsw_5.qmd
          - text: BSWorkshop - Finance Data Analysis
            href: pnote/bsw_6.qmd            
          - text: Shiny Workshop - Prof's Prototype
            href: https://tskam.shinyapps.io/prototype-ShinyIDEA/
          - text: Exploration 0 - Explore with Geospatial Data
            href: pnote/test0.qmd          
          - text: Exploration 1 - Pareto Chart
            href: pnote/test1.qmd
          - text: Exploration 2 - Pyramid & Other Charts
            href: pnote/test2.qmd
          - text: Exploration 3 - Interactive & Animated Pyramid Chart
            href: pnote/test3.qmd
          - text: Exploration 4 - Interactive Heatmap Chart
            href: pnote/test4.qmd
          - text: Exploration 5 - Time-Series Visualisation
            href: pnote/test5.qmd           
          - text: Personal Note
            href: pnote/note1.qmd
          - text: Tableau Note
            href: pnote/tableauNote.qmd
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    highlight-style: solarized
    
editor: visual

