project:
  type: website

website:
  google-analytics: "G-PKMQ2W4ZRC"
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Take-home Exercise [1]
            href: Hands-on_Ex1.1.qmd
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise [1]
            href: in-class_ex/in-class_ex1/In-class_Ex1.qmd
            
      - text: Projects
        menu: 
          - text: Class Project 1
            href: class_project/project_1/xxx.qmd
     
      - text: References & Notes
        menu: 
          - text: Exploration 1 - Pareto Chart
            href: pnote/test1.qmd
          - text: Exploration 2 - Pyramid Chart
            href: pnote/test2.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

