project:
  type: website

website:
  google-analytics: "G-PKMQ2W4ZRC"
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Ex[1] DataVis with ggplot2
            href: handsOn_ex1.html
          - text: Ex[2] DataVis with Advanced ggplot2
            href: handsOn_ex2.html
          - text: Ex[3] Programming Interactive Data Visualisation
            href: handsOn_ex3.html
            
      - text: In-class Exercises
        menu: 
          - text: Ex[1] S & P Summary with Tableau
            href: https://public.tableau.com/shared/5GXCKXPQD?:display_count=n&:origin=viz_share_link
          - text: Ex[3] Programming Interactive Data Visualisation
            href: inClass/inClass_ex03/inClass_ex3.html
            
      - text: Take-home Exercises
        menu: 
          - text: Ex[1] Trellis Population Pyramids
            href: takeHome/th_ex1/th_ex1.html
          - text: Ex[1] DataViz Makeover for Trellis Population Pyramids
            href: takeHome/th_ex2/th_ex2.html
     
      - text: Workshop & Notes
        menu:
          - text: BSWorkshop - Programming Statistical Graphics
            href: pnote/bsw_3.qmd
          - text: BSWorkshop - Build Statistical Model
            href: pnote/bsw_4.qmd
          - text: BSWorkshop - Build Predictive Model
            href: pnote/bsw_5.qmd
          - text: BSWorkshop - Finance Data Analysis
            href: pnote/bsw_6.qmd            
          - text: Shiny Workshop - Prof's Prototype
            href: https://tskam.shinyapps.io/prototype-ShinyIDEA/
          - text: Exploration 0 - Explore with Geospatial Data
            href: pnote/test0.qmd          
          - text: Exploration 1 - Pareto Chart
            href: pnote/test1.qmd
          - text: Exploration 2 - Pyramid & Other Charts
            href: pnote/test2.qmd
          - text: Exploration 3 - Interactive & Animated Pyramid Chart
            href: pnote/test3.qmd
          - text: Exploration 4 - Interactive Heatmap Chart
            href: pnote/test4.qmd
          - text: Exploration 5 - Time-Series Visualisation
            href: pnote/test5.qmd           
          - text: Personal Note
            href: pnote/note1.qmd
          - text: Tableau Note
            href: pnote/tableauNote.qmd
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    

editor: visual

